import Head from 'next/head';
import { useRouter } from 'next/router';

import { Button } from 'antd';
import styles from '@/styles/home.module.scss';

const Home = () => {
  const router = useRouter();

  const onButtonClick = () => {
    router.push('/dashboard');
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button type="primary" onClick={onButtonClick}>
          Go to dashboard
        </Button>
      </main>
    </>
  );
};

export default Home;
